### ISSUE TITLE
Flashing commands get cut halfway through on VP46xx devices

### ISSUE THREAD

**Issue by filipleple** [Dasharo/osfv-scripts#47]
Any flashrom operation output (read, write, probe) ends up cut in half like so:

```
osfv_cli rte --rte_ip 192.168.10.228 flash probe
DUT model retrieved from snipeit: VP4670
Probing flash...
Executing command: flashrom -p linux_spi:dev=/dev/spidev1.0,spispeed=16000 -c MX25L12835F/MX25L12845E/MX25L12865E
flashrom v1.3.0 on Linux 5.4.69 (armv7l)
flashrom is free software, get the source code at https://flashrom.org


Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).



```

**Comment by macpijan** [comment]
This is fixed by this MR: https://github.com/Dasharo/osfv-scripts/pull/48

These commits to be specific:
- https://github.com/Dasharo/osfv-scripts/pull/48/commits/2fda8d407fae0d1cc2d7a31e17c799e28ed9b0f8
- https://github.com/Dasharo/osfv-scripts/pull/48/commits/05ffee18cef4eb6090f06b2b8132d56167ce4a7d

The underlying problem was that the stderr was not printed, and the error reason was not presented clearly.
